-- MILAD FEST - RLS Fix SQL
-- Run this in: Supabase Dashboard → SQL Editor → New Query

ALTER TABLE madrasas DISABLE ROW LEVEL SECURITY;
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE results DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE group_registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE program_registrations DISABLE ROW LEVEL SECURITY;
