import sys
import re

with open('App.js', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "⚙️ മാസ്റ്റർ സെറ്റിങ്സ് (Admin Control Panel)": "⚙️ Master Settings (Admin Control Panel)",
    "🚩 ടീമുകൾ": "🚩 Teams",
    "📂 കാറ്റഗറികൾ": "📂 Categories",
    "🧑‍🎓 വിദ്യാർത്ഥികൾ": "🧑‍🎓 Students",
    "🏆 പ്രോഗ്രാമുകൾ": "🏆 Programs",
    "📝 മാർക്ക് എൻട്രി": "📝 Mark Entry",
    "⚙️ പോയിന്റ് ഘടന": "⚙️ Point Structure",
    "🚩 പുതിയ ടീം ചേർക്കുക": "🚩 Add New Team",
    "ഉദാ: Team A": "eg: Team A",
    "ചേർക്കുക (Add Team)": "Add Team",
    "📜 നിലവിലുള്ള ടീമുകൾ": "📜 Existing Teams",
    "ടീമുകൾ ഒന്നും ചേർത്തിട്ടില്ല.": "No teams added.",
    "📂 പുതിയ കാറ്റഗറി ചേർക്കുക": "📂 Add New Category",
    "ഉദാ: Junior": "eg: Junior",
    "ഏതൊക്കെ ക്ലാസ്? (ഉദാ: 1 മുതൽ 4 വരെ)": "Which classes? (eg: 1 to 4)",
    "ചേർക്കുക (Add Category)": "Add Category",
    "📜 നിലവിലുള്ള കാറ്റഗറികൾ": "📜 Existing Categories",
    "കാറ്റഗറികൾ ഒന്നും ചേർത്തിട്ടില്ല.": "No categories added.",
    "📚 ക്ലാസ്:": "📚 Class:",
    "🧑‍🎓 പുതിയ വിദ്യാർത്ഥിയെ ചേർക്കുക": "🧑‍🎓 Add New Student",
    "വിദ്യാർത്ഥിയുടെ പേര്": "Student Name",
    "രജിസ്റ്റർ നമ്പർ / ചെസ്റ്റ് നമ്പർ": "Register Number / Chest Number",
    "ടീം തിരഞ്ഞെടുക്കുക": "Select Team",
    "കാറ്റഗറി & വിഭാഗം തിരഞ്ഞെടുക്കുക": "Select Category & Division",
    "ആൺകുട്ടി (Boy)": "Boy",
    "പെൺകുട്ടി (Girl)": "Girl",
    "ചേർക്കുക (Add Student)": "Add Student",
    "📜 രജിസ്റ്റർ ചെയ്ത വിദ്യാർത്ഥികൾ": "📜 Registered Students",
    "കുട്ടികൾ ആരും രജിസ്റ്റർ ചെയ്തിട്ടില്ല.": "No students registered.",
    "പേര്": "Name",
    "രജിസ്റ്റർ നമ്പർ": "Register Number",
    "🏆 പുതിയ മത്സരം (Program) ചേർക്കുക": "🏆 Add New Program",
    "മത്സരത്തിന്റെ പേര് (ഉദാ: പ്രസംഗം)": "Program Name (eg: Speech)",
    "മത്സര കോഡ് (ഉദാ: P101)": "Program Code (eg: P101)",
    "ആൺകുട്ടികൾ (Boys)": "Boys",
    "പെൺകുട്ടികൾ (Girls)": "Girls",
    "പൊതുവായത് (Common)": "Common",
    "SINGLE (വ്യക്തിഗതം)": "SINGLE (Individual)",
    "GROUP (ഗ്രൂപ്പ് ഇനം)": "GROUP (Group Event)",
    "ചേർക്കുക (Add Program)": "Add Program",
    "📜 പ്രോഗ്രാമുകൾ": "📜 Programs",
    "പ്രോഗ്രാമുകൾ ഒന്നും ചേർത്തിട്ടില്ല.": "No programs added.",
    "കോഡ്": "Code",
    "വിഭാഗം:": "Division:",
    "ഇനം:": "Type:",
    "📝 മാർക്ക് എൻട്രി (Mark Entry System)": "📝 Mark Entry System",
    "① കാറ്റഗറി & വിഭാഗം തിരഞ്ഞെടുക്കുക": "① Select Category & Division",
    "-- കാറ്റഗറി & വിഭാഗം --": "-- Category & Division --",
    "② മത്സരം തിരഞ്ഞെടുക്കുക": "② Select Program",
    "-- മത്സരം തിരഞ്ഞെടുക്കുക --": "-- Select Program --",
    "ആദ്യം കാറ്റഗറി തിരഞ്ഞെടുക്കുക": "Select Category First",
    "③ വിദ്യാർത്ഥിയെ തിരഞ്ഞെടുക്കുക": "③ Select Student",
    "-- വിദ്യാർത്ഥിയെ തിരഞ്ഞെടുക്കുക --": "-- Select Student --",
    "ഒന്നാം സ്ഥാനം (First)": "First Place",
    "രണ്ടാം സ്ഥാനം (Second)": "Second Place",
    "മൂന്നാം സ്ഥാനം (Third)": "Third Place",
    "സ്ഥാനമില്ല (No Place)": "No Place",
    "കാറ്റഗറി തിരഞ്ഞെടുക്കുക": "Select Category",
    "കാറ്റഗറി": "Category",
    "-- തിരഞ്ഞെടുക്കുക --": "-- Select --",
    "പ്രോഗ്രാം": "Program",
    "ലിംഗഭേദം": "Gender",
    "ഈ പ്രോഗ്രാമിൽ ഫലങ്ങൾ ഇല്ല.": "No results for this program.",
    "രജിസ്റ്റർ നമ്പർ അടിക്കുക...": "Enter Register Number...",
    "ഈ രജിസ്റ്റർ നമ്പരിൽ വിദ്യാർത്ഥിയെ കണ്ടെത്താനായില്ല.": "No student found with this register number.",
    "മത്സരം": "Program",
    "സ്ഥാനം": "Place",
    "ഗ്രേഡ്": "Grade",
    "പോയിന്റ്": "Points",
    "ആകെ പോയിന്റ്:": "Total Points:",
    "വിദ്യാർത്ഥി റിപ്പോർട്ട്": "Student Report",
    "ഫലങ്ങൾ ഒന്നും ഇല്ല.": "No results.",
    "📥 റിപ്പോർട്ട് ഡൗൺലോഡ് / പ്രിന്റ്ട് ചെയ്യുക": "📥 Download / Print Report",
    "ഫലങ്ങൾ ഒന്നും ഇതുവരെ പ്രഖ്യാപിച്ചിട്ടില്ല.": "No results announced yet.",
    "വിഭാഗം": "Division",
    "ഈ കാറ്റഗറിയിൽ / വിഭാഗത്തിൽ ഫലങ്ങൾ ഒന്നും ഇല്ല.": "No results in this category/division.",
    "ടീം:": "Team:",
    "വിദ്യാർത്ഥി": "Student",
    "ഒഴിവാക്കുക": "Delete",
    "ചാമ്പ്യൻ": "Champions",
    "ഫലങ്ങൾ (Results)": "Results",
    "പ്രോഗ്രാം വിജയികൾ": "Program Winners",
    "പ്രഖ്യാപിച്ച ഫലങ്ങൾ": "Results History",
    "-- കാറ്റഗറി തിരഞ്ഞെടുക്കുക --": "-- Select Category --",
    "പൊതുവായത്": "General"
}

for mal, eng in replacements.items():
    content = content.replace(mal, eng)

with open('App.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Replaced Malayalam text with English successfully.")
